Implement self-explanatory basic version of undefined reference error emission.
For example, before this CL, we have:
  Error: undefined reference to `f'
Now, we have:
  Error: test.o:test.cpp:function main: undefined reference to `f(int)'

Users should not forget to re-generate configure.

This CL doesn't depend on DWARF information.
We will implement DWARF version for more clear line number information later.